### ISSUE TITLE
The VERSION constant is set at the global level

### ISSUE THREAD

**Issue by babney** [DannyBen/victor#18]
Hi! We recently started using your gem to render SVGs, but I saw some weird test breakage in our app after adding it. Looking into the issue, I found that we had a test in our app that expects the VERSION constant at the top level to not be set. Including this gem causes ::VERSION to be set as Victor::VERSION.

I'm pretty sure this is because of the "include Victor" line in lib/victor.rb. Removing that would mean using Victor::SVG, Victor::CSS, and Victor::Attributes at the top level as well. But, you probably wouldn't have to change any code within the gem, and if someone else had an SVG, CSS, or Attributes class at the top level there wouldn't be any conflicts.

**Comment by DannyBen** [comment]
Thanks, looking into it now.

**Comment by DannyBen** [comment]
Hey - you were right, it was not a very polite behavior.

I have patched it in #19 - do you want to give it a shot before I release a new gem version?
If so, just use this in your Gemfile:

```ruby
gem 'victor', github: 'DannyBen/victor', branch: 'no-global-include'
```

**Comment by babney** [comment]
Can do. I'll let you know.

**Comment by babney** [comment]
Looks good. Many thanks for the quick fix!

**Comment by DannyBen** [comment]
Cool. Will release a new version now.

**Comment by DannyBen** [comment]
Version 0.2.1 includes this fix and live on rubygems.
