### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by Ox16** [DannyBen/victor#20]
Is possible to add small function?
I have 2 shapes or shape and text.
I need information this shape is collision with other?

meybe other function add put other shape on right , distance 3cm or 3 px.
please look at agg library

**Comment by DannyBen** [comment]
This is a library for writing SVG images from Ruby, not for anything else. If you can write it in SVG, you can (or should be able to-) write it with Victor.

If you want to check collision between two shapes, you should implement it or use a library that implements it outside of victor, and then use victor to write your shapes.
