### ISSUE TITLE
Support for nested SVGs

### ISSUE THREAD

**Issue by bastianovish** [DannyBen/victor#29]
Hello! 
I can't find any documentation for nesting SVG. When you compose svgs with the append operator (<<) to a SVG, the svg tag is removed from the new svg object.

The goal is to have something like this: 
`
<svg id='main'>
    ...
    <svg id='nested1'>...</svg>
    <svg id='nested2'>...</svg>
</svg>
`

Can be done with the actual gem, or it should be implemented?

**Comment by bastianovish** [comment]
Thank you for the quick response. I guess I didn't figure out how the gem works, but now is more clear for me.
The use case Im trying to achieve is something like this: [https://codepen.io/bastiansp/pen/YOpdbg](https://codepen.io/bastiansp/pen/YOpdbg) 
Insert external images and resize/crop it inline in the SVG and then compose it in another SVG taking advantage of the BBOX of internal SVG and positioning in the main SVG coordinate system so I don't need to use a `g translate(x,y)` tag
I did it with the second option you gave me, with the combination of template and render. Seems more readable for me.
Thanks!

**Comment by DannyBen** [comment]
I am glad it works for you.

The gem is incredibly simple, the [80 lines `SVG` class][1] of course being the heart of it.

Victor just makes it easy to translate anything your write from Ruby to SVG elements, by using `#method_missing`. Everything around it is just for some extra convenience.

Also, I have intentionally kept the documentation relatively short, and instead provided quite a few [documented examples][2]. 

If you believe there should be an example of your nesting SVGs, feel free to propose one.

[1]: https://github.com/DannyBen/victor/blob/master/lib/victor/svg.rb
[2]: https://github.com/DannyBen/victor/tree/master/examples#examples
