### ISSUE TITLE
XML escaping

### ISSUE THREAD

**Issue by md5** [DannyBen/victor#37]
This gem looks really great for a simple SVG builder, but I noticed it isn't doing XML escaping:

```console
$ ruby -rvictor -e 'puts Victor::SVG.new.build { text { _ "&" } }'
<text>
&
</text>
```

The `&` should be escaped to `&amp;` to be valid XML. Any plans to add this functionality?

**Comment by DannyBen** [comment]
Hmm. This requires some thought.

Implementing it will mean that Victor needs to have knowledge of what should or shouldn't be escaped (texts, URIs etc), and escaping can easily be done before passing any argument that needs escaping to `#build`.

BTW, yoru example can be shortened to:

```shell
$ ruby -rvictor -e 'puts Victor::SVG.new.build { text "&" }'
```

**Comment by DannyBen** [comment]
I have created a quick PR that escapes texts.

Can be tested by running this self contained file:

```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
  git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
  gem "victor", github: 'DannyBen/victor', branch: 'xml-escape'
end

svg = Victor::SVG.new

svg.build do 
  text "Tom & Jerry"
  g do
    _ "Dumb & Dumber"
  end
end

puts svg.to_s
```

I am guessing we should also encode attributes.

**Comment by md5** [comment]
@DannyBen how about `href`? URLs pretty frequently have `&` and should be escaped when used in an SVG `href` attribute

**Comment by md5** [comment]
The example at https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href could be adapted to use a URI that includes `&`

**Comment by DannyBen** [comment]
Ok, I have added attribute encoding also and updated the sample code above.

Do you mind testing this to see it does what you wanted it to do?

**Comment by md5** [comment]
@DannyBen just spent 10 minutes playing around with this and it looks great. Thanks for the quick turnaround!

**Comment by DannyBen** [comment]
Cool. I will implement tests and release a version today or tomorrow.

**Comment by DannyBen** [comment]
Thank you for your suggestion.

Version 0.2.7 is now released on Rubygems with XML escaping.

**Comment by md5** [comment]
Thanks!
