### ISSUE TITLE
The 'use' element outputs 'xlink-href='，shoud it be xlink:href=?

### ISSUE THREAD

**Issue by kematy** [DannyBen/victor#45]
<use x="-4.024320022636485" y="16.2355472813216" xlink-href="#sz1-33" transform="translate(200.0,230.35547281321598) scale(10,10)"/>

**Comment by DannyBen** [comment]
Post a sample code and expected vs actual result in the description please.

**Comment by kematy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            I modified  the attributes.rb file line 26 to be mapped.join(' ').gsub('xlink-href','xlink:href'),and everything is OK.module Victor  # Handles conversion from a Hash of attributes, to an XML string or  # a CSS string.  class Attributes    attr_reader :attributes    def initialize(attributes={})      @attributes = attributes    end    def to_s      mapped = attributes.map do |key, value|        key = key.to_s.tr '_', '-'        if value.is_a? Hash          style = Attributes.new(value).to_style          "#{key}=\"#{style}\""        elsif value.is_a? Array          "#{key}=\"#{value.join ' '}\""        else          "#{key}=#{value.to_s.encode(xml: :attr)}"        end      end      mapped.join(' ').gsub('xlink-href','xlink:href') ##modified by qinjb    end
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                151711064
                            
                    
                        
                            
                                    151711064@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 2/5/2020 19:55，Danny Ben Shitrit<notifications@github.com> wrote： 


Post a sample code and expected vs actual result in the description please.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DannyBen** [comment]
I am sorry, I really don't understand what you are trying to do and what is the issue.

Please the most minimal, properly formatted Ruby code that causes the error, otherwise I cannot help.

**Comment by DannyBen** [comment]
1. You do not need to change anything in Victor to make `xlink:href` work.
2. The `xlink:href` syntax is [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href).

Here is how to use both syntaxes:

```ruby
require 'victor'

svg = Victor::SVG.new

svg.build do 
  circle id: 'my_circle', cx: 5, cy: 5, r: 4, stroke: :blue
  use href: "#my_circle", x: 10, fill: :blue
  
  # xlink:href is deprecated in SVG 2, but can also be used like this
  use 'xlink:href': "#my_circle", x: 10, fill: :blue
end

puts svg.render
```

Output:

```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg ...snip...>

<svg>

<circle id="my_circle" cx="5" cy="5" r="4" stroke="blue"/>
<use href="#my_circle" x="10" fill="blue"/>
<use xlink:href="#my_circle" x="10" fill="blue"/>

</svg>
```
