### ISSUE TITLE
Conversion utility

### ISSUE THREAD

**Issue by gingermusketeer** [DannyBen/victor#46]
Hi,

I have started using this gem to generate SVGs for CNC milling and one of the use cases I have is using an existing SVG as a starting point for the generation of the desired SVG. I created a utility that takes an SVG as input and converts it to a `victor` script. Is this something you think could be included in the gem?

Script is below:

```ruby
require "nokogiri"
require "stringio"
require "byebug"

input = ARGF
doc = Nokogiri::XML(input)

svg = doc.children.last
raise "not an SVG" if svg.name != "svg"

RAW_NODES = ["text", "style"]

def get_attrs(node)
  node.attributes.values.reduce({}) do |acc, attr|
    name = attr.name
    value = attr.value
    key = attr.respond_to?(:prefix) ? "#{attr.prefix}:#{name}" : name
    acc[key] = value
    acc
  end
end

def process_node(node, out)
  children = node.children
  unless children.empty?
    out.puts "do"
    process_nodes(children, out)
    out.puts "end"
  end
end

def process_nodes(nodes, out)
  nodes.each do |node|
    attrs = get_attrs(node)
    output = true
    params = attrs.empty? ? "" : "(#{attrs.inspect})"
    name = node.name
    if RAW_NODES.include?(name)
      inner_text = node.text
      output = inner_text.strip.length > 0
      params = " #{inner_text.inspect}"
    end
    if output
      out.write "#{node.name}#{params} "
      process_node(node, out) unless RAW_NODES.include?(name)
      out.puts
    end
  end
end

result = StringIO.new
result.puts 'require "victor"'
result.puts
result.write "svg = Victor::SVG.new( "
result.write get_attrs(svg).inspect
result.puts ")"
result.puts "svg.build do"
process_nodes(svg.children, result)
result.puts "end"
result.puts 'svg.save "convert_test"'
result.rewind
str = result.read

puts str.gsub("=>", ":")

```

Usage is: `ruby convert.rb [svg_filename]`. To get improved formatting I pipe it through the `rufo` formatter.

**Comment by DannyBen** [comment]
Well, that's a neat idea and I am open to including it, under these assumptions:

1. The code needs to be converted to a nice and clear class
2. This class should be compliant with Ruby coding standards (i.e. not add any code smells, short methods etc.).
3. The conversion needs to work on a wide variety of SVGs, and not only the ones you encounter.
4. The code comes with adequate testing (== full coverage).

Are you interested in trying to tackle any of these issues?

**Comment by DannyBen** [comment]
Closing this issue, since we implemented it here:
https://github.com/dannyben/victor-cli
