### ISSUE TITLE
Combine existing SVG files

### ISSUE THREAD

**Issue by 00dav00** [DannyBen/victor#53]
Hi there, I have a use case that I'm not sure how to address with this gem.
I need to conbine 2 SVG files:
- An SVG logo 
- An SVG QR code generated by [this gem](https://github.com/whomwah/rqrcode)

I've checked `victor-cli` a little bit and I think it can help with me with this problem, just not sure how.
Is there a tool or method I'm missing that can accomplish that?

Thanks!

**Comment by DannyBen** [comment]
Victor was not designed for this, it was designed to generate SVG from within Ruby, from scratch.

However, you might be able to use the [`#append`](https://github.com/DannyBen/victor#composite-svg) (aka `<<` operator) feature, which allows you to merge any object that responds to `#to_s`, and returns an SVG string.

Notice, you will need to obtain the SVG string without any of its surrounding `<svg>` tags - only the "body".

Here is a sample, hopefully get you on the right track. This takes to SVG strings, and merges them into one SVG object, while transforming (moving) one of them to a certain position.

```ruby
require 'victor'
include Victor

logo = '<rect x="0" y="0" width="50" height="50" fill="red"/>'
qrcode = '<circle cx="50" cy="60" r="20" fill="yellow"/>'

svg = SVG.new viewBox: '0 0 100 100', style: { background: "#ddd" }
svg.build do
  append logo
  g(transform: "translate(10  10)") { append qrcode }
end

svg.save 'merged'
```

Remember, the `#append` method only needs a string, so if you are using the QR code gem, and if it has a method that returns the SVG string itself (without root node), you may be able to do it all from within Ruby.

**Comment by 00dav00** [comment]
Thanks for the quick reply @DannyBen, the info helps a lot.

I've found this method in `victor-cli` which I think will help me too:
```ruby
Victor::CLI::SVGNode.load_file
```

**Comment by 00dav00** [comment]
Closing the issue, never the less I think it would be nice to be able to open existing SVG to append things to them. ;)
