### ISSUE TITLE
how to code stops for a lineargradient

### ISSUE THREAD

**Issue by Rashidwi** [DannyBen/victor#54]
Hi, I've had a play but I can't quite see how to code this in victor. Suggestions please :)

  <defs>
    <linearGradient id="myGradient" gradientTransform="rotate(90)">
      <stop offset="5%"  stop-color="gold" />
      <stop offset="95%" stop-color="red" />
    </linearGradient>
  </defs>

**Comment by DannyBen** [comment]
Well, unless I am missing something, this should be easy.

First of all, you should know that there is a [victor CLI](https://github.com/DannyBen/victor-cli) that also allows you to convert actual SVG back to Ruby Victor code. So I just went to [this example](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient), and saved it as "test.svg" and then executed:

```
$ victor convert test.svg test.rb
```

Which gave me this:

```ruby
setup viewBox: "0 0 10 10"

build do
  defs do
    linearGradient id: "myGradient", gradientTransform: "rotate(90)" do
      stop offset: "5%", stop_color: "gold"
      stop offset: "95%", stop_color: "red"
    end
  end

  circle cx: 5, cy: 5, r: 4, fill: "url('#myGradient')"
end
```

Does this work?

**Comment by Rashidwi** [comment]
Yes, thanks, that did the job. I hadn't clocked the need for a block.

Many thanks R :)
