### ISSUE TITLE
How to add a .png image from my PC to the svg canvas?

### ISSUE THREAD

**Issue by Cuber01** [DannyBen/victor#57]
Hello.

I want to display my .png image on the svg canvas with victor.
While I can display an image from the internet, I can't display any image from my PC.

I'm asking about the svg ``<image>`` tag. 
In html I can do:
```html
<body>

<svg width="200" height="200">
  <image href="/home/user/Pictures/Screenshot.png", height="200" width="200"/>
</svg>

</body>
```
And it will display my png image on the svg canvas.

In victor, I tried to do this in a few different ways, but the only code that displayed anything was:
```rb
require 'victor'

svg = Victor::SVG.new width: 1000, height: 1000, style: { background: '#ddd' }

svg.build do 

  image href: "file:///home/user/Pictures/Screenshot.png", height: 200, width: 200   
  # if you will replace "file:///home/user/Pictures/Screenshot.png", with an image address from the internet, it works
  # "/home/user/Pictures/Screenshot.png" won't display anything at all

end

svg.save 'image'
```
Unfortunately the image displayed was not my image, but this error:
![image](https://user-images.githubusercontent.com/67684800/115209393-d5dafa00-a0fd-11eb-807e-241fbd25bee4.png)

Sorry, if this is some sort of a simple mistake but I'm sure that both the path and the image are correct.

**Comment by DannyBen** [comment]
Victor does not have any opinion about tags and image paths. It is a one-to-one Ruby to SVG converter. 

Your HTML example did not work for me. I am not sure you can use absolute paths.

If you put the images in the same directory as the SVG file (or in a child directory) it works.

Example:

```ruby
# test.rb
require 'victor/script'

setup viewBox: "0 0 200 200"

build do
  image href: "img/logo.png", height: 200, width: 200
end

save 'test.svg'
```

Run it and get `test.svg` with this content:

```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg viewBox="0 0 200 200" width="100%" height="100%" 
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">


<image href="img/logo.png" height="200" width="200"/>

</svg>
``

which renders as expected for me (assuming you have `img/logo.png`).

**Comment by Cuber01** [comment]
Thanks for the reply. The issue was with all the renderers I tried, the only tool that can render it properly seems to be a browser (at least Firefox and Chrome).
