### ISSUE TITLE
tspan elements always rendered with space inbetween

### ISSUE THREAD

**Issue by noniq** [DannyBen/victor#62]
Let’s say I want to create styled text like this:

<img width="377" alt="expected" src="https://user-images.githubusercontent.com/244158/175944448-a268889a-3be6-4219-b317-e7cabf3ab93d.png">

Sample program:
```ruby 
require 'victor'

svg = Victor::SVG.new
svg.build do
  text font_size: 20, y: 20, font_family: 'Verdana, sans-serif' do
    tspan 'im', font_weight: "bold"
    tspan 'plicit vs. '
    tspan 'ex', font_weight: "bold"
    tspan 'plicit'
  end
end
svg.save("test.svg")
```

The output of this program, however, gets rendered like this:

<img width="379" alt="actual" src="https://user-images.githubusercontent.com/244158/175944867-a6ce5557-8533-4518-a2fd-e678c87d2afa.png">

The apparent cause is that the generated XML has each `tspan` element on a separate line:
```xml
<text font-size="20" y="20" font-family="Verdana, sans-serif">
<tspan font-weight="bold">
im
</tspan>
<tspan>
plicit vs. 
</tspan>
<tspan font-weight="bold">
ex
</tspan>
<tspan>
plicit
</tspan>
</text>
```

If I manually edit the XML to look like this, the text gets rendered as expected:
```xml
<text font-size="20" y="20" font-family="Verdana, sans-serif">
<tspan font-weight="bold">im</tspan><tspan>plicit vs. </tspan><tspan font-weight="bold">ex</tspan><tspan>plicit</tspan>
</text>
```

This is the same behaviour know from HTML (i.e. white space, including line breaks, is significant in elements that may contain text nodes).

The fix would obviously be easy: Just render all `tspan` elements in a single line. However, this would not be fully backwards compatible – for example the rendered SVG from https://github.com/DannyBen/victor/issues/35#issuecomment-497909742 would have no more spaces between the words. I’m not really sure what to do about that.

**Comment by DannyBen** [comment]
Thanks for the detailed example, and thorough research on the topic.

You are absolutely right - it is a problem. I will need to think if and how it is addressed. I am unlikely to add any specific handling for `tspan`. If anything, it will be some global solution for stating "do not add newlines after this element".

**Comment by DannyBen** [comment]
I have added the option to specify a glue other than "\n".
https://github.com/DannyBen/victor#xml-newlines

**Comment by noniq** [comment]
Great solution! Thanks a lot for fixing this so quickly. 🙏

**Comment by DannyBen** [comment]
Version 0.3.4 is [released](https://github.com/DannyBen/victor/releases/tag/v0.3.4) with this change, thanks for bringing it to my attention.
