### ISSUE TITLE
Variable scope issues

### ISSUE THREAD

**Issue by larry104** [DannyBen/victor#64]
It seems that when using victor within a class that class variables are not known anymore.

```ruby
require "victor"

@test =1

svg = Victor::SVG.new(width: '100%', height: '100%', viewBox: '-10 -10 200 250')
puts @test.inspect
svg.build do
   puts @test.inspect
      g(transform: "matrix(1 0 0 -1 0 240") do
      puts @test.inspect
   end
end
```

The output is
```
1
nil
nil 
```

Only instance variables are known e.g. if I would define @@test instead of @test. This seems a rather unusual behavior for a gem. Any comments?

**Comment by DannyBen** [comment]
Anything in the `build` block is evaluated in the context of the `Victor::SVG` class, not your own class.

https://github.com/DannyBen/victor/blob/baad031f47f534c8b598a689f7633794ed6cbc33/lib/victor/svg_base.rb#L32-L34

Use standard variables or methods:

```ruby
require 'victor'

svg = Victor::SVG.new

x, y = 10, 20

svg.build do
  rect x: x, y: y
end

puts svg.render
```

**Comment by larry104** [comment]
ok. It might be worth adding a few comments about that into the documentation. I also saw in one example to just derive from Victor::SVG maybe that's then the better solution.

Thanks!

**Comment by DannyBen** [comment]
It depends on how complex your image is.
If you expect it to receive parameters, and be capable of generating different outputs, then yes.

Hopefully the examples are covering enough use cases.

**Comment by larry104** [comment]
Yeah, it's a quite complex image. Thanks a lot for you quick feedback!

**Comment by DannyBen** [comment]
Then you can maybe also take a look at a real world example, which is inheriting from `Victor::SVGBase`.
https://github.com/DannyBen/icodi/blob/master/lib/icodi.rb
