### ISSUE TITLE
Convert to other image formats

### ISSUE THREAD

**Issue by elalemanyo** [DannyBen/victor#70]
Hi,
It may not have much to do with the gem, but some good idea to be able to have other formats besides svg, such as jpg or png.
BTW: Thank you very much for the gem

**Comment by DannyBen** [comment]
Victor is exclusively an SVG generator.
You can convert SVG to any other format using other tools, such as ImageMagick or my favorite - [rsvg-convert](https://manpages.ubuntu.com/manpages/trusty/man1/rsvg-convert.1.html)

**Comment by DannyBen** [comment]
Yup. That is also an option. Keep in mind that ImageMagick for me sometimes converted even simple SVGs incorrectly.
